id = "gemini"
name = "Gemini"
description = "Syntax highlighting for Gemini's gemtext markup language."
version = "0.0.1"
schema_version = 1
authors = ["Christian Lee Seibold <christian.seibold32@outlook.com"]
repository = "https://github.com/clseibold/gemini-zed"

[grammars.gemini]
repository = "https://git.sr.ht/~nbsp/tree-sitter-gemini"
commit = "b60a42df3f76bd4e8f988465309d705a007dc506"
